name: CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: "22.11.0"

      - name: Install dependencies
        run: npm install

      - name: Build app bundle
        run: npm run build:prod

      - name: Copy index.html to 404.html in contacto
        run: cp dist/madereria/browser/contacto/index.html dist/madereria/browser/contacto/404.html

      - name: Copy index.html to 404.html in products
        run: cp dist/madereria/browser/productos/index.html dist/madereria/browser/productos/404.html

      - name: Copy index.html to 404.html
        run: cp dist/madereria/browser/index.html dist/madereria/browser/404.html

      - name: Copy index.html to 404.html
        run: cp dist/madereria/browser/index.csr.html dist/madereria/browser/404.csr.html

      - name: List files for debugging
        run: ls -R dist/madereria/browser

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/madereria/browser
